name: WayToVenue
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.14.0+2
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  bloc: ^6.0.2
  pin_entry_text_field: ^0.1.4
  flutter_bloc: ^6.0.2
  flutter_svg: ^0.19.0
  google_fonts: ^1.1.0
  url_launcher: ^5.5.1
  image_picker: ^0.6.7+7
  mdi: ^4.0.0
  firebase_storage: ^4.0.0
  firebase_messaging: ^7.0.0
  intl: ^0.16.1
  time_formatter: ^1.0.0+5
  flutter_local_notifications: ^1.4.4+4
  fluttertoast: ^7.0.4
  avatar_glow: ^1.2.0
  country_code_picker: ^1.5.0
  clipboard: ^0.1.2+8
  searchable_dropdown: ^1.1.3
  share: ^0.6.5+2
  flare_flutter: ^2.0.6
  image_downloader: ^0.20.1
  cached_network_image: ^2.3.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo.png'
